## THEME
import = ["~/.config/alacritty/rose-pine.toml"]
## THEME
[window]
opacity = 0.86

## FONT
[font]
size = 13.0

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "Bold Italic"
## FONT

[shell]
  program = "/usr/bin/tmux"
  args = ["-l", "-c", "tmux attach || tmux"]
