## THEME
import = ["~/.config/alacritty/rose-pine.toml"]
## THEME
[window]
opacity = 0.90
blur = true

[env]
TERM = "xterm-256color"
## FONT
[font]
size = 13.0

[font.normal]
family = "CaskaydiaCove Nerd Font Propo"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font Propo"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font Propo"
style = "Italic"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Propo"
style = "Bold Italic"
## FONT

[shell]
program = "/usr/bin/tmux"
args = ["-l", "-c", "zellij attach --index 0 || zellij"]
