#!/usr/bin/env bash

tmux_env_script="$HOME/.config/tmux/scripts/utils/envs"
source "$tmux_env_script"

touch "$fzf_session_history"

all_panes=$("$tmux_utils_scripts/panes")

result=$(
  printf '%s' "$all_panes" |
  fzf \
  --with-nth=1,2,3,4,5 \
  --preview "tmux capture-pane -t {1} -p -e -S -100 | tail -n 48" \
  --bind "ctrl-x:execute(tmux kill-pane -t {1})+reload($HOME/.config/tmux/scripts/panes)" \
  --bind "ctrl-r:refresh-preview" \
  --bind "enter:become(echo {1} {2} {3} {4} {5})" \
  --layout=reverse
)

[ -z "$result" ] && exit 0
result=$(echo "$result" | xargs)
printf '%s\n' "$result" >> "$fzf_session_history"

pane=$(awk '{print $1}' <<< "$result")
tmux switch-client -t $pane
