#!/usr/bin/zsh

export ZSH_PLUGINS=$HOME/.config/zsh/plugins

plugins=(zsh-vi-mode zsh-z zsh-syntax-highlighting)

for plugin in $plugins
do
	plugin_path="$ZSH_PLUGINS/$plugin/$plugin.plugin.zsh"
	if [[ -f  "$plugin_path" ]]; then
		source "$plugin_path"
	fi
done
