#!/usr/bin/env bash

tmux_env_script="$HOME/.config/tmux/scripts/utils/envs"
source "$tmux_env_script"

current_pane=$(tmux display-message -p '#S:#I.#P - #W')
panes=$(tmux list-panes -a -F '#S:#I.#P - #W')

previous_pane=$(
  tail -n2 "$fzf_session_history" |
  head -n1 |
  grep -F -f <(printf '%s\n' "$panes")
)

if [ -n "$previous_pane" ]; then
  panes=$(printf '%s\n' "$panes" | grep -v "$previous_pane")
  panes=$(printf '%s\n%s\n' "$previous_pane" "$panes")
fi

all_panes=$(
  printf '%s\n' "$panes" |
  grep -v "$current_pane" |
  grep -v -E "^\n\$"
)

printf '%s\n' "$all_panes"
