unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

set -g prefix M-space

set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on
set-option -g status-position top
set-window-option -g pane-base-index 1

set-option -g history-file ~/.tmux_history
setw -g automatic-rename on

setw -g mode-keys vi
set-option -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key l select-pane -R
bind-key k select-pane -U

bind -n M-h resize-pane -L 2
bind -n M-l resize-pane -R 2
bind -n M-j resize-pane -D 2
bind -n M-k resize-pane -U 2

bind -n C-w new-window
bind -n C-n next-window
bind -n C-p previous-window
bind -n C-M-p switch-client -p
bind -n C-M-w new-session
bind -n C-M-n switch-client -n
bind -n C-M-n switch-client -n

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind -n C-g display-popup -w 80 -h 20 -E "tmux new-session -A -s popup"

bind -n M-1 split-window -h -c "#{pane_current_path}"
bind -n M-2 split-window -v -c "#{pane_current_path}"
bind -n M-3 split-window -v -l 10 -c "#{pane_current_path}"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @catppuccin_custom_plugin_dir $HOME/.config/tmux/custom/catppuccin/
set -g @catppuccin_status_modules_right 'git_status application session'
set -g @catppuccin_flavour 'macchiato'

set -g default-terminal "${TERM}"
 
set-option -sg escape-time 10

run '~/.config/tmux/plugins/tpm/tpm'
