unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g mouse on
set -g prefix C-s

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on


setw -g mode-keys vi
set-option -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel


bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'


set -g @dracula-show-powerline true
set -g @dracula-fixed-location "Madrid"
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g status-position top

set-option -sg escape-time 10

run '~/.tmux/plugins/tpm/tpm'
